
version: "2.1"

parameters:
  dockerize_me:
    type: boolean
    default: true
  pokus_go_version:
    type: string
    default: "1.18.3"
  project_folder:
    type: string
    default: "./steps/go.dev/doc/tutorial/getting-started/hello-pokus"
  gopkg_auth_secret_user:
    type: string
    default: "pokus"
  gopkg_auth_secret_pwd:
    type: string
    default: "pokus"
  dockerhub_auth_secret_user:
    type: string
    default: "pokus"
  dockerhub_auth_secret_pwd:
    type: string
    default: "pokus"


jobs:
  unit_test_hello_pokus:
    # <<: *pokus-jobs-common
    docker:
      - image: cimg/go:<< pipeline.parameters.pokus_go_version >>
    environment:
      BASH_ENV: /etc/profile
      POKUS_PRJ_DIR: << pipeline.parameters.project_folder >>
    steps:
      # <<: *pokus-common-steps
      - run:
          name: "env setup"
          command: |
              echo 'export PATH="$GOPATH"/bin:"$PATH"' >> "$BASH_ENV"
              echo 'export GIT_SHA1="$CIRCLE_SHA1"' >> "$BASH_ENV"
      - checkout
      - run:
          name: "switch to prj folder"
          command: |
              cd ${POKUS_PRJ_DIR}
      - run:
          name: "run unit tests"
          command: | 
              echo "# go Hello Pokus unit tests!"

  build_hello_pokus:
    # <<: *pokus-jobs-common
    docker:
      - image: "cimg/go:<<pipeline.parameters.pokus_go_version>>"
    environment:
      BASH_ENV: /etc/profile
      POKUS_PRJ_DIR: "<<pipeline.parameters.project_folder>>"
    steps:
      # <<: *pokus-common-steps
      - run:
          name: "env setup"
          command: |
              echo 'export PATH="$GOPATH"/bin:"$PATH"' >> "$BASH_ENV"
              echo 'export GIT_SHA1="$CIRCLE_SHA1"' >> "$BASH_ENV"
      - checkout
      - run:
          name: "Switch project folder"
          command: |
              cd ${POKUS_PRJ_DIR}
      - run:
          name: "Build"
          command: | 
              echo "# go Build Hello Pokus !"

workflows:
  version: 2
    when: << pipeline.parameters.dockerize_me >> 
  hello_pokus_gomod_ci:
    jobs:
      - unit_test_hello_pokus
      - build_hello_pokus:
          requires:
            - unit_test_hello_pokus
